/**
 * Salestream API
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SalestreamApi) {
      root.SalestreamApi = {};
    }
    root.SalestreamApi.CreateEmail = factory(root.SalestreamApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The CreateEmail model module.
   * @module model/CreateEmail
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CreateEmail</code>.
   * @alias module:model/CreateEmail
   * @class
   * @param emailId {String} 
   * @param to {Array.<String>} 
   * @param subject {String} 
   * @param message {String} 
   */
  var exports = function(emailId, to, subject, message) {
    var _this = this;

    _this['emailId'] = emailId;
    _this['to'] = to;
    _this['subject'] = subject;
    _this['message'] = message;
  };

  /**
   * Constructs a <code>CreateEmail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateEmail} obj Optional instance to populate.
   * @return {module:model/CreateEmail} The populated <code>CreateEmail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('emailId')) {
        obj['emailId'] = ApiClient.convertToType(data['emailId'], 'String');
      }
      if (data.hasOwnProperty('to')) {
        obj['to'] = ApiClient.convertToType(data['to'], ['String']);
      }
      if (data.hasOwnProperty('cc')) {
        obj['cc'] = ApiClient.convertToType(data['cc'], ['String']);
      }
      if (data.hasOwnProperty('bcc')) {
        obj['bcc'] = ApiClient.convertToType(data['bcc'], ['String']);
      }
      if (data.hasOwnProperty('subject')) {
        obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('draft')) {
        obj['draft'] = ApiClient.convertToType(data['draft'], 'Boolean');
      }
      if (data.hasOwnProperty('reminderEnabled')) {
        obj['reminderEnabled'] = ApiClient.convertToType(data['reminderEnabled'], 'Boolean');
      }
      if (data.hasOwnProperty('reminderDate')) {
        obj['reminderDate'] = ApiClient.convertToType(data['reminderDate'], 'Number');
      }
      if (data.hasOwnProperty('schedule')) {
        obj['schedule'] = ApiClient.convertToType(data['schedule'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} emailId
   */
  exports.prototype['emailId'] = undefined;
  /**
   * @member {Array.<String>} to
   */
  exports.prototype['to'] = undefined;
  /**
   * @member {Array.<String>} cc
   */
  exports.prototype['cc'] = undefined;
  /**
   * @member {Array.<String>} bcc
   */
  exports.prototype['bcc'] = undefined;
  /**
   * @member {String} subject
   */
  exports.prototype['subject'] = undefined;
  /**
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {Boolean} draft
   */
  exports.prototype['draft'] = undefined;
  /**
   * @member {Boolean} reminderEnabled
   */
  exports.prototype['reminderEnabled'] = undefined;
  /**
   * @member {Number} reminderDate
   */
  exports.prototype['reminderDate'] = undefined;
  /**
   * @member {Number} schedule
   */
  exports.prototype['schedule'] = undefined;



  return exports;
}));


