/**
 * Salestream API
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SalestreamApi) {
      root.SalestreamApi = {};
    }
    root.SalestreamApi.CreateContactDetails = factory(root.SalestreamApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The CreateContactDetails model module.
   * @module model/CreateContactDetails
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CreateContactDetails</code>.
   * @alias module:model/CreateContactDetails
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>CreateContactDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateContactDetails} obj Optional instance to populate.
   * @return {module:model/CreateContactDetails} The populated <code>CreateContactDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contact')) {
        obj['contact'] = ApiClient.convertToType(data['contact'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CreateContactDetails.ContactEnum} contact
   */
  exports.prototype['contact'] = undefined;


  /**
   * Allowed values for the <code>contact</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ContactEnum = {
    /**
     * value: "direct"
     * @const
     */
    "direct": "direct",
    /**
     * value: "fax"
     * @const
     */
    "fax": "fax",
    /**
     * value: "home"
     * @const
     */
    "home": "home",
    /**
     * value: "mobile"
     * @const
     */
    "mobile": "mobile",
    /**
     * value: "office"
     * @const
     */
    "office": "office",
    /**
     * value: "url"
     * @const
     */
    "url": "url",
    /**
     * value: "other"
     * @const
     */
    "other": "other"  };


  return exports;
}));


