/**
 * Salestream API
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SalestreamApi) {
      root.SalestreamApi = {};
    }
    root.SalestreamApi.CreateOpportunity = factory(root.SalestreamApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The CreateOpportunity model module.
   * @module model/CreateOpportunity
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CreateOpportunity</code>.
   * @alias module:model/CreateOpportunity
   * @class
   * @param value {Number} 
   * @param estCloseDate {Number} 
   * @param assignee {String} 
   * @param confidence {Number} 
   */
  var exports = function(value, estCloseDate, assignee, confidence) {
    var _this = this;

    _this['value'] = value;
    _this['est_close_date'] = estCloseDate;
    _this['assignee'] = assignee;
    _this['confidence'] = confidence;
  };

  /**
   * Constructs a <code>CreateOpportunity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateOpportunity} obj Optional instance to populate.
   * @return {module:model/CreateOpportunity} The populated <code>CreateOpportunity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('value')) {
        obj['value'] = ApiClient.convertToType(data['value'], 'Number');
      }
      if (data.hasOwnProperty('est_close_date')) {
        obj['est_close_date'] = ApiClient.convertToType(data['est_close_date'], 'Number');
      }
      if (data.hasOwnProperty('assignee')) {
        obj['assignee'] = ApiClient.convertToType(data['assignee'], 'String');
      }
      if (data.hasOwnProperty('confidence')) {
        obj['confidence'] = ApiClient.convertToType(data['confidence'], 'Number');
      }
      if (data.hasOwnProperty('contact')) {
        obj['contact'] = ApiClient.convertToType(data['contact'], 'String');
      }
      if (data.hasOwnProperty('comment')) {
        obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} value
   */
  exports.prototype['value'] = undefined;
  /**
   * @member {Number} est_close_date
   */
  exports.prototype['est_close_date'] = undefined;
  /**
   * @member {String} assignee
   */
  exports.prototype['assignee'] = undefined;
  /**
   * @member {Number} confidence
   */
  exports.prototype['confidence'] = undefined;
  /**
   * @member {String} contact
   */
  exports.prototype['contact'] = undefined;
  /**
   * @member {String} comment
   */
  exports.prototype['comment'] = undefined;



  return exports;
}));


