/**
 * Salestream API
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CreateLeadAddresses', 'model/CreateLeadContacts'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CreateLeadAddresses'), require('./CreateLeadContacts'));
  } else {
    // Browser globals (root is window)
    if (!root.SalestreamApi) {
      root.SalestreamApi = {};
    }
    root.SalestreamApi.CreateLead = factory(root.SalestreamApi.ApiClient, root.SalestreamApi.CreateLeadAddresses, root.SalestreamApi.CreateLeadContacts);
  }
}(this, function(ApiClient, CreateLeadAddresses, CreateLeadContacts) {
  'use strict';



  /**
   * The CreateLead model module.
   * @module model/CreateLead
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CreateLead</code>.
   * @alias module:model/CreateLead
   * @class
   * @param company {String} 
   */
  var exports = function(company) {
    var _this = this;

    _this['company'] = company;
  };

  /**
   * Constructs a <code>CreateLead</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateLead} obj Optional instance to populate.
   * @return {module:model/CreateLead} The populated <code>CreateLead</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('company')) {
        obj['company'] = ApiClient.convertToType(data['company'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('contacts')) {
        obj['contacts'] = ApiClient.convertToType(data['contacts'], [CreateLeadContacts]);
      }
      if (data.hasOwnProperty('addresses')) {
        obj['addresses'] = ApiClient.convertToType(data['addresses'], [CreateLeadAddresses]);
      }
      if (data.hasOwnProperty('custom_fields')) {
        obj['custom_fields'] = ApiClient.convertToType(data['custom_fields'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {String} company
   */
  exports.prototype['company'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Array.<module:model/CreateLeadContacts>} contacts
   */
  exports.prototype['contacts'] = undefined;
  /**
   * @member {Array.<module:model/CreateLeadAddresses>} addresses
   */
  exports.prototype['addresses'] = undefined;
  /**
   * @member {Object} custom_fields
   */
  exports.prototype['custom_fields'] = undefined;



  return exports;
}));


