/**
 * Salestream API
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalestreamApi);
  }
}(this, function(expect, SalestreamApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalestreamApi.CreateEmail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateEmail', function() {
    it('should create an instance of CreateEmail', function() {
      // uncomment below and update the code to test CreateEmail
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be.a(SalestreamApi.CreateEmail);
    });

    it('should have the property emailId (base name: "emailId")', function() {
      // uncomment below and update the code to test the property emailId
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "to")', function() {
      // uncomment below and update the code to test the property to
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be();
    });

    it('should have the property cc (base name: "cc")', function() {
      // uncomment below and update the code to test the property cc
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be();
    });

    it('should have the property bcc (base name: "bcc")', function() {
      // uncomment below and update the code to test the property bcc
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be();
    });

    it('should have the property draft (base name: "draft")', function() {
      // uncomment below and update the code to test the property draft
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be();
    });

    it('should have the property reminderEnabled (base name: "reminderEnabled")', function() {
      // uncomment below and update the code to test the property reminderEnabled
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be();
    });

    it('should have the property reminderDate (base name: "reminderDate")', function() {
      // uncomment below and update the code to test the property reminderDate
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be();
    });

    it('should have the property schedule (base name: "schedule")', function() {
      // uncomment below and update the code to test the property schedule
      //var instance = new SalestreamApi.CreateEmail();
      //expect(instance).to.be();
    });

  });

}));
