/**
 * Salestream API
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalestreamApi);
  }
}(this, function(expect, SalestreamApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalestreamApi.CreateLeadAddresses();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateLeadAddresses', function() {
    it('should create an instance of CreateLeadAddresses', function() {
      // uncomment below and update the code to test CreateLeadAddresses
      //var instance = new SalestreamApi.CreateLeadAddresses();
      //expect(instance).to.be.a(SalestreamApi.CreateLeadAddresses);
    });

    it('should have the property line1 (base name: "line1")', function() {
      // uncomment below and update the code to test the property line1
      //var instance = new SalestreamApi.CreateLeadAddresses();
      //expect(instance).to.be();
    });

    it('should have the property line2 (base name: "line2")', function() {
      // uncomment below and update the code to test the property line2
      //var instance = new SalestreamApi.CreateLeadAddresses();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new SalestreamApi.CreateLeadAddresses();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new SalestreamApi.CreateLeadAddresses();
      //expect(instance).to.be();
    });

    it('should have the property zip (base name: "zip")', function() {
      // uncomment below and update the code to test the property zip
      //var instance = new SalestreamApi.CreateLeadAddresses();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new SalestreamApi.CreateLeadAddresses();
      //expect(instance).to.be();
    });

  });

}));
