/**
 * Salestream API
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CreateContact', 'model/CreateContactDetails', 'model/CreateEmail', 'model/CreateLead', 'model/CreateLeadAddresses', 'model/CreateLeadContacts', 'model/CreateLeadDetails', 'model/CreateNote', 'model/CreateOpportunity', 'model/CreateSms', 'model/CreateTask', 'model/CreateWebhook', 'model/ErrorResponse', 'model/InlineObject', 'model/RegisterResource', 'model/SuccessResponse', 'model/UnregisterResource', 'model/UpdateContact', 'model/UpdateEmail', 'model/UpdateLead', 'model/UpdateNote', 'model/UpdateOpportunity', 'model/UpdateSms', 'model/UpdateTask', 'model/UpdateWebhook', 'api/ActivityApi', 'api/CommonApi', 'api/CustomFieldsApi', 'api/LeadApi', 'api/LeadContactApi', 'api/LeadOpportunityApi', 'api/TaskApi', 'api/WebhookApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/CreateContact'), require('./model/CreateContactDetails'), require('./model/CreateEmail'), require('./model/CreateLead'), require('./model/CreateLeadAddresses'), require('./model/CreateLeadContacts'), require('./model/CreateLeadDetails'), require('./model/CreateNote'), require('./model/CreateOpportunity'), require('./model/CreateSms'), require('./model/CreateTask'), require('./model/CreateWebhook'), require('./model/ErrorResponse'), require('./model/InlineObject'), require('./model/RegisterResource'), require('./model/SuccessResponse'), require('./model/UnregisterResource'), require('./model/UpdateContact'), require('./model/UpdateEmail'), require('./model/UpdateLead'), require('./model/UpdateNote'), require('./model/UpdateOpportunity'), require('./model/UpdateSms'), require('./model/UpdateTask'), require('./model/UpdateWebhook'), require('./api/ActivityApi'), require('./api/CommonApi'), require('./api/CustomFieldsApi'), require('./api/LeadApi'), require('./api/LeadContactApi'), require('./api/LeadOpportunityApi'), require('./api/TaskApi'), require('./api/WebhookApi'));
  }
}(function(ApiClient, CreateContact, CreateContactDetails, CreateEmail, CreateLead, CreateLeadAddresses, CreateLeadContacts, CreateLeadDetails, CreateNote, CreateOpportunity, CreateSms, CreateTask, CreateWebhook, ErrorResponse, InlineObject, RegisterResource, SuccessResponse, UnregisterResource, UpdateContact, UpdateEmail, UpdateLead, UpdateNote, UpdateOpportunity, UpdateSms, UpdateTask, UpdateWebhook, ActivityApi, CommonApi, CustomFieldsApi, LeadApi, LeadContactApi, LeadOpportunityApi, TaskApi, WebhookApi) {
  'use strict';

  /**
   * Salestream_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var SalestreamApi = require('index'); // See note below*.
   * var xxxSvc = new SalestreamApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new SalestreamApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new SalestreamApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new SalestreamApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The CreateContact model constructor.
     * @property {module:model/CreateContact}
     */
    CreateContact: CreateContact,
    /**
     * The CreateContactDetails model constructor.
     * @property {module:model/CreateContactDetails}
     */
    CreateContactDetails: CreateContactDetails,
    /**
     * The CreateEmail model constructor.
     * @property {module:model/CreateEmail}
     */
    CreateEmail: CreateEmail,
    /**
     * The CreateLead model constructor.
     * @property {module:model/CreateLead}
     */
    CreateLead: CreateLead,
    /**
     * The CreateLeadAddresses model constructor.
     * @property {module:model/CreateLeadAddresses}
     */
    CreateLeadAddresses: CreateLeadAddresses,
    /**
     * The CreateLeadContacts model constructor.
     * @property {module:model/CreateLeadContacts}
     */
    CreateLeadContacts: CreateLeadContacts,
    /**
     * The CreateLeadDetails model constructor.
     * @property {module:model/CreateLeadDetails}
     */
    CreateLeadDetails: CreateLeadDetails,
    /**
     * The CreateNote model constructor.
     * @property {module:model/CreateNote}
     */
    CreateNote: CreateNote,
    /**
     * The CreateOpportunity model constructor.
     * @property {module:model/CreateOpportunity}
     */
    CreateOpportunity: CreateOpportunity,
    /**
     * The CreateSms model constructor.
     * @property {module:model/CreateSms}
     */
    CreateSms: CreateSms,
    /**
     * The CreateTask model constructor.
     * @property {module:model/CreateTask}
     */
    CreateTask: CreateTask,
    /**
     * The CreateWebhook model constructor.
     * @property {module:model/CreateWebhook}
     */
    CreateWebhook: CreateWebhook,
    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject: InlineObject,
    /**
     * The RegisterResource model constructor.
     * @property {module:model/RegisterResource}
     */
    RegisterResource: RegisterResource,
    /**
     * The SuccessResponse model constructor.
     * @property {module:model/SuccessResponse}
     */
    SuccessResponse: SuccessResponse,
    /**
     * The UnregisterResource model constructor.
     * @property {module:model/UnregisterResource}
     */
    UnregisterResource: UnregisterResource,
    /**
     * The UpdateContact model constructor.
     * @property {module:model/UpdateContact}
     */
    UpdateContact: UpdateContact,
    /**
     * The UpdateEmail model constructor.
     * @property {module:model/UpdateEmail}
     */
    UpdateEmail: UpdateEmail,
    /**
     * The UpdateLead model constructor.
     * @property {module:model/UpdateLead}
     */
    UpdateLead: UpdateLead,
    /**
     * The UpdateNote model constructor.
     * @property {module:model/UpdateNote}
     */
    UpdateNote: UpdateNote,
    /**
     * The UpdateOpportunity model constructor.
     * @property {module:model/UpdateOpportunity}
     */
    UpdateOpportunity: UpdateOpportunity,
    /**
     * The UpdateSms model constructor.
     * @property {module:model/UpdateSms}
     */
    UpdateSms: UpdateSms,
    /**
     * The UpdateTask model constructor.
     * @property {module:model/UpdateTask}
     */
    UpdateTask: UpdateTask,
    /**
     * The UpdateWebhook model constructor.
     * @property {module:model/UpdateWebhook}
     */
    UpdateWebhook: UpdateWebhook,
    /**
     * The ActivityApi service constructor.
     * @property {module:api/ActivityApi}
     */
    ActivityApi: ActivityApi,
    /**
     * The CommonApi service constructor.
     * @property {module:api/CommonApi}
     */
    CommonApi: CommonApi,
    /**
     * The CustomFieldsApi service constructor.
     * @property {module:api/CustomFieldsApi}
     */
    CustomFieldsApi: CustomFieldsApi,
    /**
     * The LeadApi service constructor.
     * @property {module:api/LeadApi}
     */
    LeadApi: LeadApi,
    /**
     * The LeadContactApi service constructor.
     * @property {module:api/LeadContactApi}
     */
    LeadContactApi: LeadContactApi,
    /**
     * The LeadOpportunityApi service constructor.
     * @property {module:api/LeadOpportunityApi}
     */
    LeadOpportunityApi: LeadOpportunityApi,
    /**
     * The TaskApi service constructor.
     * @property {module:api/TaskApi}
     */
    TaskApi: TaskApi,
    /**
     * The WebhookApi service constructor.
     * @property {module:api/WebhookApi}
     */
    WebhookApi: WebhookApi
  };

  return exports;
}));
