/**
 * Salestream API
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SalestreamApi);
  }
}(this, function(expect, SalestreamApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SalestreamApi.ActivityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ActivityApi', function() {
    describe('leadIdActivityEmailEmailIdDelete', function() {
      it('should call leadIdActivityEmailEmailIdDelete successfully', function(done) {
        //uncomment below and update the code to test leadIdActivityEmailEmailIdDelete
        //instance.leadIdActivityEmailEmailIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadIdActivityEmailEmailIdPut', function() {
      it('should call leadIdActivityEmailEmailIdPut successfully', function(done) {
        //uncomment below and update the code to test leadIdActivityEmailEmailIdPut
        //instance.leadIdActivityEmailEmailIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadIdActivityEmailPost', function() {
      it('should call leadIdActivityEmailPost successfully', function(done) {
        //uncomment below and update the code to test leadIdActivityEmailPost
        //instance.leadIdActivityEmailPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadIdActivityGet', function() {
      it('should call leadIdActivityGet successfully', function(done) {
        //uncomment below and update the code to test leadIdActivityGet
        //instance.leadIdActivityGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadIdActivityNoteNoteIdDelete', function() {
      it('should call leadIdActivityNoteNoteIdDelete successfully', function(done) {
        //uncomment below and update the code to test leadIdActivityNoteNoteIdDelete
        //instance.leadIdActivityNoteNoteIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadIdActivityNoteNoteIdPut', function() {
      it('should call leadIdActivityNoteNoteIdPut successfully', function(done) {
        //uncomment below and update the code to test leadIdActivityNoteNoteIdPut
        //instance.leadIdActivityNoteNoteIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadIdActivityNotePost', function() {
      it('should call leadIdActivityNotePost successfully', function(done) {
        //uncomment below and update the code to test leadIdActivityNotePost
        //instance.leadIdActivityNotePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadIdActivitySmsPost', function() {
      it('should call leadIdActivitySmsPost successfully', function(done) {
        //uncomment below and update the code to test leadIdActivitySmsPost
        //instance.leadIdActivitySmsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadIdActivitySmsSmsIdDelete', function() {
      it('should call leadIdActivitySmsSmsIdDelete successfully', function(done) {
        //uncomment below and update the code to test leadIdActivitySmsSmsIdDelete
        //instance.leadIdActivitySmsSmsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leadIdActivitySmsSmsIdPut', function() {
      it('should call leadIdActivitySmsSmsIdPut successfully', function(done) {
        //uncomment below and update the code to test leadIdActivitySmsSmsIdPut
        //instance.leadIdActivitySmsSmsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
